import { type Template } from '@pdfme/common';

export type PDFData = [
  {
    qr: string;
    ubicacion: string;
    nombre: string;
    fecha: string;
    datos: Array<[string, string, string, string, string]>; // [nombre, ID, telefono, dni, si/no]
  },
];

export const presentismoPDFSchema: Template = {
  schemas: [
    {
      field1: {
        type: 'readOnlyText',
        content: 'Nombre del evento:',
        position: {
          x: 9,
          y: 9.3,
        },
        width: 45,
        height: 10,
        rotate: 0,
        alignment: 'left',
        verticalAlignment: 'top',
        fontSize: 13,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: '#000000',
        backgroundColor: '',
        opacity: 1,
        strikethrough: false,
        underline: false,
        readOnly: true,
        required: false,
        fontName: 'NotoSansJP-Regular',
      },
      field2: {
        type: 'readOnlyText',
        content: 'Fecha:',
        position: {
          x: 9.26,
          y: 17.5,
        },
        width: 45,
        height: 10,
        rotate: 0,
        alignment: 'left',
        verticalAlignment: 'top',
        fontSize: 13,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: '#000000',
        backgroundColor: '',
        opacity: 1,
        strikethrough: false,
        underline: false,
        readOnly: true,
        required: false,
        fontName: 'NotoSansJP-Regular',
      },
      'field2 copy': {
        type: 'readOnlyText',
        content: 'Ubicación:',
        position: {
          x: 9.47,
          y: 25.91,
        },
        width: 45,
        height: 10,
        rotate: 0,
        alignment: 'left',
        verticalAlignment: 'top',
        fontSize: 13,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: '#000000',
        backgroundColor: '',
        opacity: 1,
        strikethrough: false,
        underline: false,
        readOnly: true,
        required: false,
        fontName: 'NotoSansJP-Regular',
      },
      ubicacion: {
        type: 'text',
        position: {
          x: 34.13,
          y: 26.24,
        },
        required: true,
        content: 'Juan B. Justo 1579',
        width: 45,
        height: 10,
        rotate: 0,
        alignment: 'left',
        verticalAlignment: 'top',
        fontSize: 13,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: '#000000',
        backgroundColor: '',
        opacity: 1,
        strikethrough: false,
        underline: false,
        fontName: 'NotoSansJP-Regular',
      },
      nombre: {
        type: 'text',
        position: {
          x: 52.92,
          y: 9.67,
        },
        required: true,
        content: 'T17 E8',
        width: 45,
        height: 10,
        rotate: 0,
        alignment: 'left',
        verticalAlignment: 'top',
        fontSize: 13,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: '#000000',
        backgroundColor: '',
        opacity: 1,
        strikethrough: false,
        underline: false,
        fontName: 'NotoSansJP-Regular',
      },
      fecha: {
        type: 'text',
        position: {
          x: 25.4,
          y: 17.5,
        },
        required: true,
        content: '11/08/2024',
        width: 45,
        height: 10,
        rotate: 0,
        alignment: 'left',
        verticalAlignment: 'top',
        fontSize: 13,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: '#000000',
        backgroundColor: '',
        opacity: 1,
        strikethrough: false,
        underline: false,
        fontName: 'NotoSansJP-Regular',
      },
      field7: {
        type: 'line',
        position: {
          x: 0,
          y: 38.73,
        },
        width: 210,
        height: 0.73,
        rotate: 0,
        opacity: 1,
        readOnly: true,
        color: '#303030',
        required: false,
      },
      datos: {
        type: 'table',
        position: {
          x: 4.7,
          y: 42.47,
        },
        width: 202.65,
        height: 52.932,
        content:
          '[["Aylen Katherine Naiquen Alegre Fanelli","99999","54 9 11 6534 4651 980","46581349","Sí"],["Ariel Colton","1948","1136005044","46501954",""]]',
        showHead: true,
        head: ['Nombre', 'ID', 'Núm. de teléfono', 'DNI', '¿Asistió?'],
        headWidthPercentages: [
          22.13974216629657, 12.103719467061442, 29.901924500370086,
          21.21800723743734, 14.63660662883455,
        ],
        tableStyles: {
          borderWidth: 0.3,
          borderColor: '#000000',
        },
        headStyles: {
          fontName: 'NotoSansJP-Regular',
          fontSize: 13,
          characterSpacing: 0,
          alignment: 'left',
          verticalAlignment: 'middle',
          lineHeight: 1,
          fontColor: '#ffffff',
          borderColor: '',
          backgroundColor: '#2980ba',
          borderWidth: {
            top: 0,
            right: 0,
            bottom: 0,
            left: 0,
          },
          padding: {
            top: 5,
            right: 5,
            bottom: 5,
            left: 5,
          },
        },
        bodyStyles: {
          fontName: 'NotoSansJP-Regular',
          fontSize: 13,
          characterSpacing: 0,
          alignment: 'left',
          verticalAlignment: 'middle',
          lineHeight: 1,
          fontColor: '#000000',
          borderColor: '#888888',
          backgroundColor: '',
          alternateBackgroundColor: '#f5f5f5',
          borderWidth: {
            top: 0.1,
            right: 0.1,
            bottom: 0.1,
            left: 0.1,
          },
          padding: {
            top: 5,
            right: 5,
            bottom: 5,
            left: 5,
          },
        },
        columnStyles: {},
        required: true,
      },
      qr: {
        type: 'qrcode',
        content: 'https://pdfme.com/',
        position: {
          x: 175.17,
          y: 5.11,
        },
        backgroundColor: '#ffffff',
        barColor: '#000000',
        width: 30,
        height: 30,
        rotate: 0,
        opacity: 1,
        required: true,
      },
    },
  ],
  basePdf: {
    width: 210,
    height: 297,
    padding: [0, 0, 0, 0],
  },
  pdfmeVersion: '4.0.0',
};
